version: "3"

services:
  zfile:
    container_name: zfile
    image: zhaojun1998/zfile:latest
    ports:
      - "8080:8080" 
    volumes: 
      - data:/
    restart: always

  lsky:
    container_name: lsky
    image: halcyonazure/lsky-pro-docker:latest
    ports:
      - "8089:8089" 
    volumes: 
      - data2:/var/www/html/
    restart: always

  ac:
    container_name: ac
    image: ghcr.io/binary-husky/gpt_academic_with_latex:master
    ports:
      - "12303:12303" 
    volumes: 
      - data1:/var/www/html/
    restart: always
    environment:
      - API_KEY=sk-pz4NgxsmsWz7dwjTwsCttQ3rsGRC5dlLf7IhtTg80CDhUzn6
      - WEB_PORT=12303
      - API_URL_REDIRECT={"https://api.openai.com/v1/chat/completions":"https://api.chatanywhere.com.cn/v1/chat/completions"}

volumes:
    data:
    data1:
    data2:
    # driver_opts:
    #   size: 4Gi

