version: "3"

services:
  chat:
    container_name: chat
    image: chenzhaoyu94/chatgpt-web:latest
    ports:
      - "3002:3002" 
    environment:
      - OPENAI_API_BASE_URL=https://api.chatanywhere.com.cn
      - OPENAI_API_KEY=sk-Gf0uIYDWuI0R0hNqIotYtQskwS6I1AWCbxCQiGK8qGOVl3dP
    restart: always

  lsky:
    container_name: lsky
    image: halcyonazure/lsky-pro-docker:latest
    ports:
      - "8089:8089" 
    volumes: 
      - data2:/var/www/html/
    restart: always

volumes:
    data2:
    # driver_opts:
    #   size: 4Gi

